### PR TITLE
Add findbugs plugin to the build script - Fix #6

### LINKED ISSUE #6: FindBugs
Plugin FindBugs to gradle build.

### PR DESCRIPTION
**Pull request by moghaddam**

### CODE REVIEW

**Comment by m0mus** [comment]
Does it run on every single build? I don't see that there is a specific task for it.

**Comment by moghaddam** [comment]
Yes, it's bounded by default to the "check" task, so it will be run on each build

**Comment by m0mus** [comment]
I think that it may be better to create a specific task for it, let's say "findbugs". It's not convenient to run it on every single build. What do you think?

**Comment by bravehorsie** [comment]
Do we have some policy for findbugs to use? I suppose it will take some initial work for the first build to pass. +1 for separate build or to run on demand by gradle property.

**Comment by moghaddam** [comment]
Yes, you're right. The Findbugs plugin by default introduces two tasks named 'findbugsMain' and 'findbugsTest' that are by default bounded to the 'check' step. We can prevent them to run on each build and instead call their corresponding tasks directly if needed. I just updated the branch

**Pull request merged**
